---
abstract: ~
author:
  - 'kamichidu <c.kamunagi@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Downloader
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Encode::Argv: 0
  Encode::Locale: 0
  Moose: 0
  MooseX::Getopt: 0
  namespace::clean: 0
  perl: 5.10.0
  strict: 0
  utf8: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
